
services:
    db:
        container_name: mongodb
        image: mongo:6.0
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
        volumes:
            - ./mongo:/data/db
        restart: always
        ports:
            - ${MONGO_PORT}:27017

networks:
    pokemon-vol:
        external: false