
services:
    db:
        container_name: mongodb
        image: mongo:6.0
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: pokedb
            USER: root
        volumes:
            - ./mongo:/data/db
        restart: always
        command: ["--auth"]
        ports:
            - ${MONGO_PORT}:27017

volumes:
    mongo:
        external: false